export const ALL_QUESTIONS = [
  // SCIENCE
  { cat: 'science', type: 'mc', text: 'In which year did Alexander Fleming discover penicillin?', hint: 'He noticed mold killing bacteria on a petri dish.', opts: ['1918', '1922', '1928', '1935'], answer: 2, explanation: 'Fleming discovered penicillin in 1928 when mold contaminated his culture plates.' },
  { cat: 'science', type: 'mc', text: 'When did Marie Curie win her first Nobel Prize (in Physics)?', hint: 'She was the first woman to win a Nobel Prize.', opts: ['1896', '1903', '1911', '1921'], answer: 1, explanation: 'Curie won the 1903 Nobel Prize in Physics, sharing it with her husband Pierre and Henri Becquerel.' },
  { cat: 'science', type: 'slider', text: 'Drag to the year DNA\'s double helix structure was published by Watson & Crick.', hint: 'A landmark moment in molecular biology.', sliderRange: [1940, 1970], answer: 1953, explanation: 'Watson and Crick published their model of DNA in Nature in April 1953.' },
  { cat: 'science', type: 'mc', text: 'The theory of general relativity was published by Einstein in what year?', hint: 'It was during World War I.', opts: ['1905', '1912', '1915', '1919'], answer: 2, explanation: 'Einstein published his theory of general relativity in 1915, though key tests came in 1919.' },
  { cat: 'science', type: 'slider', text: 'Drag to the year the first successful human heart transplant was performed.', hint: 'It happened in South Africa.', sliderRange: [1955, 1985], answer: 1967, explanation: 'Dr. Christiaan Barnard performed the first human heart transplant in Cape Town, South Africa in 1967.' },

  // HISTORY
  { cat: 'history', type: 'mc', text: 'In which year did the Berlin Wall fall?', hint: 'The Cold War was ending across Eastern Europe.', opts: ['1987', '1988', '1989', '1991'], answer: 2, explanation: 'The Berlin Wall fell on November 9, 1989, as communist East Germany opened its borders.' },
  { cat: 'history', type: 'slider', text: 'Drag to the year the Magna Carta was signed.', hint: 'It limited the power of the English king.', sliderRange: [1100, 1300], answer: 1215, explanation: 'King John of England signed the Magna Carta at Runnymede on June 15, 1215.' },
  { cat: 'history', type: 'mc', text: 'The French Revolution began in which year?', hint: 'The storming of the Bastille was the famous flashpoint.', opts: ['1785', '1789', '1793', '1799'], answer: 1, explanation: 'The French Revolution is generally dated from 1789 when the Estates-General convened and the Bastille was stormed.' },
  { cat: 'history', type: 'mc', text: 'In which year did World War I end?', hint: 'The armistice was signed on the 11th hour of the 11th day of the 11th month.', opts: ['1916', '1917', '1918', '1919'], answer: 2, explanation: 'WWI ended on November 11, 1918 with the signing of the Armistice.' },
  { cat: 'history', type: 'slider', text: 'Drag to the year Julius Caesar was assassinated.', hint: 'It happened on the Ides of March.', sliderRange: [-100, 0], answer: -44, explanation: 'Julius Caesar was assassinated on March 15, 44 BC (displayed as -44).' },

  // TECHNOLOGY
  { cat: 'tech', type: 'mc', text: 'When was the first iPhone released by Apple?', hint: 'Steve Jobs called it "a revolutionary product."', opts: ['2005', '2006', '2007', '2008'], answer: 2, explanation: 'Apple released the first iPhone on June 29, 2007. Steve Jobs had unveiled it in January that year.' },
  { cat: 'tech', type: 'mc', text: 'In which year was the World Wide Web invented by Tim Berners-Lee?', hint: 'He was working at CERN in Switzerland.', opts: ['1983', '1989', '1991', '1995'], answer: 1, explanation: 'Tim Berners-Lee invented the World Wide Web in 1989 and published the first web page in 1991.' },
  { cat: 'tech', type: 'slider', text: 'Drag to the year the first commercial email service launched (ARPANET email).', hint: 'It predates the public internet significantly.', sliderRange: [1965, 1990], answer: 1971, explanation: 'Ray Tomlinson sent the first network email in 1971, establishing the @ convention still used today.' },
  { cat: 'tech', type: 'mc', text: 'ChatGPT was launched publicly in which month and year?', hint: 'It rapidly became one of the fastest-growing apps in history.', opts: ['March 2022', 'November 2022', 'March 2023', 'November 2023'], answer: 1, explanation: 'ChatGPT was launched publicly on November 30, 2022 and reached 1 million users within 5 days.' },
  { cat: 'tech', type: 'slider', text: 'Drag to the year Netflix was founded (originally as a DVD rental service).', hint: 'It predates streaming by over a decade.', sliderRange: [1990, 2010], answer: 1997, explanation: 'Netflix was founded in 1997 by Reed Hastings and Marc Randolph as a DVD mail rental service.' },

  // CULTURE
  { cat: 'culture', type: 'mc', text: 'In which year did The Beatles release "Abbey Road"?', hint: 'It was the last album they recorded together.', opts: ['1967', '1968', '1969', '1970'], answer: 2, explanation: 'Abbey Road was released on September 26, 1969. It was the last album recorded by all four Beatles together.' },
  { cat: 'culture', type: 'slider', text: 'Drag to the year the first modern Olympic Games were held.', hint: 'They were held in Athens, Greece.', sliderRange: [1880, 1920], answer: 1896, explanation: 'The first modern Olympic Games were held in Athens, Greece in April 1896, revived by Pierre de Coubertin.' },
  { cat: 'culture', type: 'mc', text: 'Shakespeare\'s "Romeo and Juliet" was written approximately when?', hint: 'It was during the Elizabethan era.', opts: ['1560–1565', '1574–1578', '1594–1596', '1600–1604'], answer: 2, explanation: 'Romeo and Juliet is believed to have been written between 1594 and 1596, early in Shakespeare\'s career.' },
  { cat: 'culture', type: 'mc', text: 'In which year was the Eiffel Tower completed?', hint: 'It was built for a World\'s Fair in Paris.', opts: ['1885', '1887', '1889', '1893'], answer: 2, explanation: 'The Eiffel Tower was completed on March 31, 1889 for the 1889 World\'s Fair celebrating 100 years of the French Revolution.' },
  { cat: 'culture', type: 'slider', text: 'Drag to the year Picasso painted Guernica.', hint: 'It depicted the bombing of a Basque town during the Spanish Civil War.', sliderRange: [1920, 1960], answer: 1937, explanation: 'Picasso painted Guernica in 1937 as a protest against the bombing of the Basque town of Guernica.' },

  // SPACE
  { cat: 'space', type: 'mc', text: 'In which year did humans first land on the Moon?', hint: 'Neil Armstrong was the first to step on the lunar surface.', opts: ['1966', '1968', '1969', '1972'], answer: 2, explanation: 'Apollo 11 landed on the Moon on July 20, 1969. Neil Armstrong took his first step about 6 hours later.' },
  { cat: 'space', type: 'slider', text: 'Drag to the year the Hubble Space Telescope was launched.', hint: 'It has given us some of the deepest views of the universe.', sliderRange: [1980, 2005], answer: 1990, explanation: 'The Hubble Space Telescope was launched on April 24, 1990 aboard the Space Shuttle Discovery.' },
  { cat: 'space', type: 'mc', text: 'Sputnik, the first artificial satellite, was launched in what year?', hint: 'It triggered the Space Race between the US and USSR.', opts: ['1955', '1956', '1957', '1958'], answer: 2, explanation: 'The Soviet Union launched Sputnik 1 on October 4, 1957, beginning the Space Age.' },
  { cat: 'space', type: 'slider', text: 'Drag to the year Mars Curiosity rover landed on Mars.', hint: 'It used the "sky crane" landing system.', sliderRange: [2000, 2020], answer: 2012, explanation: 'Curiosity landed in Gale Crater on Mars on August 6, 2012, using the revolutionary sky crane system.' },
  { cat: 'space', type: 'mc', text: 'The James Webb Space Telescope launched in which year?', hint: 'It is the successor to Hubble, orbiting 1.5 million km from Earth.', opts: ['2019', '2020', '2021', '2022'], answer: 2, explanation: 'JWST launched on December 25, 2021 aboard an Ariane 5 rocket. First science images were released in July 2022.' },
];
